## Business Recommendation System

Adaptated from: 
- https://www.kaggle.com/code/sagarbapodara/coursera-course-recommendation-system-webapp

In [64]:
import os
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity as cs

import nltk
from nltk.stem.porter import PorterStemmer

In [65]:
df = pd.read_csv("user_input.csv")

In [66]:
print(type(df.bidang_keahlian[0]))

df.bidang_keahlian = df.bidang_keahlian.apply(lambda x: x.replace("[","").replace("]","").replace("'",""))
df.hobi = df.hobi.apply(lambda x: x.replace("[","").replace("]","").replace("'",""))

df

<class 'str'>


user_id              level               bidang_keahlian  \
0         0   udah_punya_usaha            kuliner, healtcare   
1         1   udah_punya_usaha            kuliner, healtcare   
2         2   udah_punya_usaha            healtcare, kuliner   
3         3   udah_punya_usaha                       kuliner   
4         4   udah_punya_usaha                     healtcare   
5         5   udah_punya_usaha  kuliner, healtcare, homecare   
6         6   udah_punya_usaha                     healtcare   
7         7   udah_punya_usaha  healtcare, homecare, kuliner   
8         8   udah_punya_usaha           homecare, healtcare   
9         9   udah_punya_usaha                      homecare   
10       10   udah_punya_usaha                      homecare   
11       11   udah_punya_usaha             homecare, kuliner   
12       12   udah_punya_usaha  homecare, healtcare, kuliner   
13       13   udah_punya_usaha           homecare, healtcare   
14       14   udah_punya_usaha                      homecare   
15       15   udah_punya_usaha  kuliner, homecare, healtcare   
16       16   udah_punya_usaha  kuliner, homecare, healtcare   
17       17   udah_punya_usaha                      homecare   
18       18   udah_punya_usaha                       kuliner   
19       19   udah_punya_usaha  kuliner, healtcare, homecare   
20       20   udah_punya_usaha            healtcare, kuliner   
21       21   udah_punya_usaha           homecare, healtcare   
22       22   udah_punya_usaha                      homecare   
23       23   udah_punya_usaha  homecare, healtcare, kuliner   
24       24   udah_punya_usaha            healtcare, kuliner   
25       25   udah_punya_usaha                     healtcare   
26       26   udah_punya_usaha                     healtcare   
27       27   udah_punya_usaha                     healtcare   
28       28   udah_punya_usaha             kuliner, homecare   
29       29   udah_punya_usaha  homecare, kuliner, healtcare   
30       30   udah_punya_usaha  kuliner, homecare, healtcare   
31       31   udah_punya_usaha  healtcare, homecare, kuliner   
32       32   udah_punya_usaha            kuliner, healtcare   
33       33   udah_punya_usaha  homecare, kuliner, healtcare   
34       34   udah_punya_usaha  healtcare, homecare, kuliner   
35       35   udah_punya_usaha             kuliner, homecare   
36       36   udah_punya_usaha  kuliner, healtcare, homecare   
37       37   udah_punya_usaha           healtcare, homecare   
38       38   udah_punya_usaha                       kuliner   
39       39   udah_punya_usaha            kuliner, healtcare   
40       40  belum_punya_usaha                      homecare   
41       41  belum_punya_usaha                     healtcare   
42       42  belum_punya_usaha                     healtcare   
43       43  belum_punya_usaha                      homecare   
44       44  belum_punya_usaha                     healtcare   
45       45  belum_punya_usaha                       kuliner   
46       46  belum_punya_usaha             kuliner, homecare   
47       47  belum_punya_usaha  kuliner, healtcare, homecare   
48       48  belum_punya_usaha                     healtcare   
49       49  belum_punya_usaha                     healtcare   

                                            hobi         modal_usaha  
0                               baca, travelling           above_100  
1                               nonton, olahraga            under_50  
2                     travelling, olahraga, baca  between_50_and_100  
3              membaca, travelling, nonton, baca            under_50  
4                                     travelling           above_100  
5                                   baca, nonton           above_100  
6                                   nonton, baca           above_100  
7         makan, baca, membaca, nonton, olahraga  between_50_and_100  
8                                 membaca, makan            under_50  
9      makan, olahraga, trave

In [67]:
df.info()
df.isnull().sum()
df.level
df.bidang_keahlian
df.hobi
df.modal_usaha

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   user_id          50 non-null     int64 
 1   level            50 non-null     object
 2   bidang_keahlian  50 non-null     object
 3   hobi             50 non-null     object
 4   modal_usaha      50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


0              above_100
1               under_50
2     between_50_and_100
3               under_50
4              above_100
5              above_100
6              above_100
7     between_50_and_100
8               under_50
9               under_50
10    between_50_and_100
11    between_50_and_100
12              under_50
13    between_50_and_100
14             above_100
15              under_50
16             above_100
17             above_100
18             above_100
19              under_50
20              under_50
21              under_50
22    between_50_and_100
23    between_50_and_100
24    between_50_and_100
25    between_50_and_100
26    between_50_and_100
27              under_50
28             above_100
29             above_100
30    between_50_and_100
31             above_100
32              under_50
33             above_100
34    between_50_and_100
35    between_50_and_100
36    between_50_and_100
37             above_100
38              under_50
39              under_50


## Preprocessing

In [68]:
df.user_id= df.user_id.astype(str)

## Tage Column

In [69]:
df["features"] = df["bidang_keahlian"] + "," + df["hobi"]  + "," + df["modal_usaha"]
df

user_id              level               bidang_keahlian  \
0        0   udah_punya_usaha            kuliner, healtcare   
1        1   udah_punya_usaha            kuliner, healtcare   
2        2   udah_punya_usaha            healtcare, kuliner   
3        3   udah_punya_usaha                       kuliner   
4        4   udah_punya_usaha                     healtcare   
5        5   udah_punya_usaha  kuliner, healtcare, homecare   
6        6   udah_punya_usaha                     healtcare   
7        7   udah_punya_usaha  healtcare, homecare, kuliner   
8        8   udah_punya_usaha           homecare, healtcare   
9        9   udah_punya_usaha                      homecare   
10      10   udah_punya_usaha                      homecare   
11      11   udah_punya_usaha             homecare, kuliner   
12      12   udah_punya_usaha  homecare, healtcare, kuliner   
13      13   udah_punya_usaha           homecare, healtcare   
14      14   udah_punya_usaha                      homecare   
15      15   udah_punya_usaha  kuliner, homecare, healtcare   
16      16   udah_punya_usaha  kuliner, homecare, healtcare   
17      17   udah_punya_usaha                      homecare   
18      18   udah_punya_usaha                       kuliner   
19      19   udah_punya_usaha  kuliner, healtcare, homecare   
20      20   udah_punya_usaha            healtcare, kuliner   
21      21   udah_punya_usaha           homecare, healtcare   
22      22   udah_punya_usaha                      homecare   
23      23   udah_punya_usaha  homecare, healtcare, kuliner   
24      24   udah_punya_usaha            healtcare, kuliner   
25      25   udah_punya_usaha                     healtcare   
26      26   udah_punya_usaha                     healtcare   
27      27   udah_punya_usaha                     healtcare   
28      28   udah_punya_usaha             kuliner, homecare   
29      29   udah_punya_usaha  homecare, kuliner, healtcare   
30      30   udah_punya_usaha  kuliner, homecare, healtcare   
31      31   udah_punya_usaha  healtcare, homecare, kuliner   
32      32   udah_punya_usaha            kuliner, healtcare   
33      33   udah_punya_usaha  homecare, kuliner, healtcare   
34      34   udah_punya_usaha  healtcare, homecare, kuliner   
35      35   udah_punya_usaha             kuliner, homecare   
36      36   udah_punya_usaha  kuliner, healtcare, homecare   
37      37   udah_punya_usaha           healtcare, homecare   
38      38   udah_punya_usaha                       kuliner   
39      39   udah_punya_usaha            kuliner, healtcare   
40      40  belum_punya_usaha                      homecare   
41      41  belum_punya_usaha                     healtcare   
42      42  belum_punya_usaha                     healtcare   
43      43  belum_punya_usaha                      homecare   
44      44  belum_punya_usaha                     healtcare   
45      45  belum_punya_usaha                       kuliner   
46      46  belum_punya_usaha             kuliner, homecare   
47      47  belum_punya_usaha  kuliner, healtcare, homecare   
48      48  belum_punya_usaha                     healtcare   
49      49  belum_punya_usaha                     healtcare   

                                            hobi         modal_usaha  \
0                               baca, travelling           above_100   
1                               nonton, olahraga            under_50   
2                     travelling, olahraga, baca  between_50_and_100   
3              membaca, travelling, nonton, baca            under_50   
4                                     travelling           above_100   
5                                   baca, nonton           above_100   
6                                   nonton, baca           above_100   
7         makan, baca, membaca, nonton, olahraga  between_50_and_100   
8                                 membaca, makan            under_50   
9      makan, olahraga, travelling, baca, nonton            under_50 

In [70]:
new_df = df[["user_id","features"]]
new_df.features = new_df.features.apply(lambda x: x.replace(","," "))
new_df.features = new_df.features.apply(lambda x: x.lower())

new_df

C:\Users\Muhammad Nur Ilmi\AppData\Local\Temp\ipykernel_9264\3855829668.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.features = new_df.features.apply(lambda x: x.replace(","," "))
C:\Users\Muhammad Nur Ilmi\AppData\Local\Temp\ipykernel_9264\3855829668.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.features = new_df.features.apply(lambda x: x.lower())


user_id                                           features
0        0      kuliner  healtcare baca  travelling above_100
1        1       kuliner  healtcare nonton  olahraga under_50
2        2  healtcare  kuliner travelling  olahraga  baca ...
3        3  kuliner membaca  travelling  nonton  baca unde...
4        4                     healtcare travelling above_100
5        5  kuliner  healtcare  homecare baca  nonton abov...
6        6                   healtcare nonton  baca above_100
7        7  healtcare  homecare  kuliner makan  baca  memb...
8        8        homecare  healtcare membaca  makan under_50
9        9  homecare makan  olahraga  travelling  baca  no...
10      10  homecare travelling  membaca  baca between_50_...
11      11  homecare  kuliner olahraga  makan  membaca  tr...
12      12  homecare  healtcare  kuliner membaca  baca  no...
13      13  homecare  healtcare makan  membaca between_50_...
14      14   homecare olahraga  nonton  baca  makan above_100
15      15  kuliner  homecare  healtcare membaca  nonton  ...
16      16  kuliner  homecare  healtcare nonton  olahraga ...
17      17  homecare membaca  olahraga  travelling  baca  ...
18      18  kuliner travelling  nonton  olahraga  membaca ...
19      19  kuliner  healtcare  homecare olahraga  membaca...
20      20  healtcare  kuliner membaca  olahraga  travelli...
21      21                homecare  healtcare nonton under_50
22      22  homecare travelling  olahraga  membaca  nonton...
23      23  homecare  healtcare  kuliner nonton  baca  mak...
24      24  healtcare  kuliner olahraga  baca  nonton betw...
25      25               healtcare membaca between_50_and_100
26      26  healtcare travelling  nonton  membaca  makan  ...
27      27  healtcare baca  nonton  olahraga  membaca  tra...
28      28      kuliner  homecare membaca  olahraga above_100
29      29  homecare  kuliner  healtcare travelling above_100
30      30  kuliner  homecare  healtcare baca  travelling ...
31      31  healtcare  homecare  kuliner olahraga  membaca...
32      32  kuliner  healtcare travelling  olahraga  makan...
33      33     homecare  kuliner  healtcare membaca above_100
34      34  healtcare  homecare  kuliner baca between_50_a...
35      35  kuliner  homecare travelling  membaca  baca be...
36      36  kuliner  healtcare  homecare travelling betwee...
37      37  healtcare  homecare travelling  baca  nonton  ...
38      38  kuliner baca  makan  travelling  nonton  memba...
39      39  kuliner  healtcare travelling  olahraga  nonto...
40      40  homecare olahraga  travelling  baca  membaca  ...
41      41       healtcare baca  travelling  nonton above_100
42      42        healtcare olahraga  baca between_50_and_100
43      43  homecare olahraga  nonton  travelling  makan  ...
44      44       healtcare travelling  makan  nonton under_50
45      45    kuliner baca  membaca  olahraga  makan under_50
46      46      kuliner  homecare travelling  makan above_100
47      47  kuliner  healtcare  homecare membaca  baca  tr...
48      48              healtcare olahraga between_50_and_100
49      49  healtcare olahraga  nonton  makan  travelling ...

In [71]:
new_df.shape

(50, 2)

In [72]:
cv = CountVectorizer(max_features = 5000)
vectors = cv.fit_transform(new_df.features).toarray()

In [73]:
porterStemmer = PorterStemmer()
def stem(txt):
    y = []
    for t in txt.split():
        y.append(porterStemmer.stem(t))
    return " ".join(y)

In [74]:
new_df.features = new_df.features.apply(stem)

C:\Users\Muhammad Nur Ilmi\AppData\Local\Temp\ipykernel_9264\1174626138.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.features = new_df.features.apply(stem)


In [75]:
similarityDistance = cs(vectors)
print(similarityDistance)

[[1.         0.4        0.73029674 ... 0.59628479 0.25819889 0.36514837]
 [0.4        1.         0.54772256 ... 0.4472136  0.51639778 0.73029674]
 [0.73029674 0.54772256 1.         ... 0.68041382 0.70710678 0.5       ]
 ...
 [0.59628479 0.4472136  0.68041382 ... 1.         0.38490018 0.54433105]
 [0.25819889 0.51639778 0.70710678 ... 0.38490018 1.         0.47140452]
 [0.36514837 0.73029674 0.5        ... 0.54433105 0.47140452 1.        ]]


In [82]:
def getRecommendation(user_id):
    index = new_df[new_df["user_id"] == user_id].index[0]
    distance = similarityDistance[index]
    userRank = sorted(list(enumerate(distance)), reverse = True, key = lambda x:x[1])[1:5]

    for i in userRank:
        print(i)
        # print(new_df.iloc[i])

In [83]:
getRecommendation("0")

(29, 0.7999999999999999)
(41, 0.7999999999999999)
(16, 0.7905694150420948)
(4, 0.7745966692414835)
